permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install phpunit
      run: sudo apt-get install -y phpunit make

    - name: check
      run: make check
