name: PHPunit
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install phpunit
      run: sudo apt-get install -y phpunit make

    - name: Create config file
      echo '<?php $home="/home/runner/work/";$extractdir="$home/d2view-extract";?>' > config.php
      
    - name: check
      run: make check
